Add dex provider (DFI-BTC)
DeFiCh/salmon pull request #107
Opened 2021-07-26 09:11 UTC by monstrobishi

#### What kind of PR is this?:

/kind feature

#### What this PR does / why we need it:

At the moment only mapping DFI-BTC pool as we can get other crypto info from various sources, Defichain DEX DFI-BTC is the best source for stable DFI pricing.

#### Which issue(s) does this PR fixes?:

Fixes #

#### Additional comments?:

2021-07-26 09:36 UTC, fuxingloh requested changes

2021-07-26 09:36 UTC, fuxingloh commented on packages/salmon-provider-dex/src/index.ts
> +    const text = await response.text()
https://github.com/DeFiCh/whale/blob/main/packages/whale-api-client/src/api/poolpair.ts

use this client instead?

2021-07-26 09:36 UTC, fuxingloh commented on packages/salmon-provider-dex/src/mapping.ts
> +  affector?: () => Promise<BigNumber>
should rename this function, affector doesn't make sense?

2021-07-27 04:22 UTC, fuxingloh requested changes

2021-07-27 04:22 UTC, fuxingloh commented on packages/salmon-provider-dex/src/index.ts
> +    const json = await whaleClient.poolpair.list(1000)
```suggestion
    const json = await whaleClient.poolpair.list(1000)
```

whale client doesn't allow calls like this, need to do pagination chaining to get all the results.

2021-07-27 04:22 UTC, fuxingloh commented on packages/salmon-provider-dex/src/index.ts
> +    const json = await whaleClient.poolpair.list(1000)
For context: https://github.com/DeFiCh/whale/issues/268

Pagination chaining: https://github.com/DeFiCh/whale/blob/abbecbac7212556af71a4405241cca38d447163e/packages/whale-api-client/__tests__/api/address.test.ts#L144

2021-07-27 04:23 UTC, fuxingloh commented on packages/salmon-provider-dex/src/index.ts
> +    const json = await whaleClient.poolpair.list(1000)
Protecting against future regression

2021-07-27 12:52 UTC, jingyi2811 approved these changes

2021-07-27 18:06 UTC, fuxingloh approved these changes

2021-07-27 18:06 UTC, fuxingloh commented on packages/salmon-provider-dex/src/index.ts
> +    let whaleResponse: ApiPagedResponse<any> = await whaleClient.poolpair.list(50)
without enforcing the types, you are taking typescript soundness out of the equation

2021-07-28 02:34 UTC, canonbrother approved these changes

2021-07-28 02:44 UTC, monstrobishi commented on packages/salmon-provider-dex/src/index.ts
> +    let whaleResponse: ApiPagedResponse<any> = await whaleClient.poolpair.list(50)
I think whale client doesn't expose the poolpair structure type

2021-07-28 02:44 UTC, merged

2021-07-28 03:59 UTC, fuxingloh commented on packages/salmon-provider-dex/src/index.ts
> +    let whaleResponse: ApiPagedResponse<any> = await whaleClient.poolpair.list(50)
https://github.com/DeFiCh/wallet/blob/31ecd6da37a55b144b2e7f02974ec9102f7d3699/app/screens/AppNavigator/screens/Dex/DexScreen.tsx#L2

2021-07-28 04:03 UTC, monstrobishi commented on packages/salmon-provider-dex/src/index.ts
> +    let whaleResponse: ApiPagedResponse<any> = await whaleClient.poolpair.list(50)
I stand corrected! I am hesitant to import from dist dir though, I think interface types should be exposed at the root level

2021-07-28 05:06 UTC, fuxingloh commented on packages/salmon-provider-dex/src/index.ts
> +    let whaleResponse: ApiPagedResponse<any> = await whaleClient.poolpair.list(50)
```ts
import { poolpairs } from '@defichain/whale-api-client'

const data: poolpairs.PoolPairData[] = []
```

I believe you can do this also