Added asset filter and malformed data test
DeFiCh/salmon pull request #40
Opened 2021-06-11 08:23 UTC by monstrobishi

#### What kind of PR is this?:

/kind chore

#### What this PR does / why we need it:

Added asset filter and malformed data test

#### Which issue(s) does this PR fixes?:

Fixes #

#### Additional comments?:

2021-06-11 09:27 UTC, monstrobishi commented
Another question is do we keep an asset price if the price is valid but the timestamp/asset name are not? I would say most likely not as those are important for us to ensure we know which asset the price belongs to and when the price occurred (could be an expired price)

2021-06-11 10:15 UTC, ivan-zynesis commented on packages/salmon-price-functions/src/price_manager.ts
> +          !asset.timestamp.isNaN()
Either let it throw here or filter them, both sound reasonable to me in different sense. If doing filtering should check all type then, since the provider can misbehave

```suggestion
          asset => asset.asset !== undefined && this.config.includes[asset] &&
            asset.timestamp !== undefined && !asset.timestamp.isNaN() &&
            asset.price!== undefined && !asset.price.isNaN()
```

2021-06-14 08:49 UTC, jingyi2811 commented on packages/salmon-price-functions/src/price_manager.ts
> +      return asset.asset !== undefined &&
Just ignore me if you think there is no problem

1) `asset.asset `seems incorrect
2) Probably you need to check whether `asset.asset `is not NaN and `asset.price` is not undefined

2021-06-14 10:45 UTC, monstrobishi commented on packages/salmon-price-functions/src/price_manager.ts
> +      return asset.asset !== undefined &&
I somewhat agree with 1, but I think can refactor later,

Have added 2 as you and Ivan suggested

2021-06-14 11:00 UTC, jingyi2811 commented on packages/salmon-price-functions/__test__/fetch_asset_prices_multiple.test.ts
> +      "c": 336.59,
Isn't this should be  "c": 605.14?

2021-06-14 11:03 UTC, jingyi2811 commented on packages/salmon-price-functions/src/price_manager.ts
> +   * @param {AssetPrice[]}
Missing params

2021-06-14 11:06 UTC, jingyi2811 commented on packages/salmon-price-functions/src/price_manager.ts
> +import { BigNumber } from '@defichain/jellyfish-json'
`import BigNumber from 'bignumber.js'`

You can see `import { BigNumber } from '@defichain/jellyfish-json'` written in other code.
They are required to be refactored one day

2021-06-14 11:08 UTC, jingyi2811 commented
A few days ago I found a typos `fatch` in this project. I think it should be `fetch`

2021-06-14 11:34 UTC, monstrobishi commented on packages/salmon-price-functions/src/price_manager.ts
> +   * @param {AssetPrice[]}
Can you elaborate, what should I add here

2021-06-14 11:37 UTC, monstrobishi commented on packages/salmon-price-functions/__test__/fetch_asset_prices_multiple.test.ts
> +      "c": 336.59,
No this is Facebook price, that structure is missing `timestamp` hence gets filtered out, the number is not important

2021-06-14 11:38 UTC, monstrobishi commented on packages/salmon-price-functions/src/price_manager.ts
> +   * @param {AssetPrice[]}
Oh I see it now, adding

2021-06-14 11:56 UTC, jingyi2811 submitted a review, later dismissed

2021-06-14 12:39 UTC, canonbrother submitted a review, later dismissed

2021-06-14 14:02 UTC, fuxingloh requested changes

2021-06-14 14:02 UTC, fuxingloh commented on packages/salmon-price-functions/src/price_manager.ts
> +    }
1. avoid closure if you can use a function instead.
2. be explicit of what that does, `check` is not good, e.g. `isTimeBefore` ...
3. `compareDate` is not explicit, use a better param
4. this entire function could be clearer

2021-06-14 15:01 UTC, monstrobishi commented on packages/salmon-price-functions/__test__/fetch_asset_prices_multiple.test.ts
> +        return finnhubbResponseTSLA
oh I did this already, I guess I haven't rebased yet?

2021-06-14 15:01 UTC, monstrobishi commented on packages/salmon-price-functions/__test__/fetch_asset_prices_multiple.test.ts
> +        return finnhubbResponseTSLA
oh it's in this existing PR https://github.com/DeFiCh/salmon/pull/38/files

2021-06-15 06:22 UTC, fuxingloh approved these changes

2021-06-15 06:23 UTC, canonbrother approved these changes

2021-06-15 07:03 UTC, jingyi2811 approved these changes

2021-06-15 07:22 UTC, merged