Refactor whale provider
DeFiCh/salmon pull request #81
Opened 2021-07-09 03:59 UTC by monstrobishi

#### What kind of PR is this?:

/kind chore

#### What this PR does / why we need it:

Refactored as per new enhancements in tx signing, need some advice if there is a better way to handle this.

#### Which issue(s) does this PR fixes?:

Fixes #

#### Additional comments?:

2021-07-09 04:03 UTC, monstrobishi commented
Keeping this draft as with the state of things it's

`+57 −51 `

Adding more code than before. This is not counting the additional tests required for the additional hd node implementation required, which also need to be adding in.

Will keep draft until jellyfish has better single keypair support.

2021-07-12 05:50 UTC, fuxingloh requested changes

2021-07-12 05:50 UTC, fuxingloh commented on packages/salmon-oracles-functions/src/oraclesManager.ts
> +    const hex = buffer.toString('hex')
```suggestion
    const hex = new CTransactionSegWit(transaction).toHex()
```

New include utility

2021-07-12 05:50 UTC, fuxingloh commented on packages/salmon-oracles-functions/src/oraclesManager.ts
> +    const hex = buffer.toString('hex')
there is `CTransactionSegWit.txId()` too if you need it

2021-07-12 07:33 UTC, fuxingloh approved these changes

2021-07-12 07:42 UTC, canonbrother approved these changes

2021-07-12 07:42 UTC, jingyi2811 approved these changes

2021-07-12 07:45 UTC, merged